talpha:
  image: kvdn
  expose:
    - "9090"
  dns: 
    - 172.17.0.1
tbeta:
  image: kvdn
  expose:
    - "9090"
  dns: 
    - 172.17.0.1
tgamma:
  image: kvdn
  expose:
    - "9090"
  dns: 
    - 172.17.0.1
test:
  image: kvdn
  expose:
    - "9090"
  dns: 
    - 172.17.0.1

discovery:
  image: "tonistiigi/dnsdock"
  expose:
    - "80"
  ports:
    - "172.17.0.1:53:53"
    - "172.17.0.1:53:53/udp"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
