talpha:
  container_name: kvdn_talpha
  image: kvdn
  expose:
    - "9090"
  dns: 
    - 172.17.0.1
tbeta:
  container_name: kvdn_tbeta
  image: kvdn
  expose:
    - "9090"
  dns: 
    - 172.17.0.1
tgamma:
  container_name: kvdn_tgamma
  image: kvdn
  expose:
    - "9090"
  dns: 
    - 172.17.0.1
test:
  container_name: kvdn_test
  image: kvdn
  expose:
    - "9090"
  dns: 
    - 172.17.0.1
discovery:
  container_name: dnsdock
  image: tonistiigi/dnsdock
  ports:
    - "172.17.0.1:53:53/udp"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  command: ["-docker=tcp://172.17.0.1:4243"]

